# develop configuration
contentDir = "exampleSite/content"
staticDir = "exampleSite/static"
themesDir = ".."

# site metadata
baseURL = "https://example.com/"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
languageCode = "zh-cn"
paginate = 10
theme = "Cocodayo"
title = "ExampleSite"

# site navigation bar
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 2
[[menu.main]]
  identifier = "category"
  name = "Category"
  url = "/categories/"
  weight = 3
[[menu.main]]
  identifier = "tag"
  name = "Tag"
  url = "/tags/"
  weight = 4
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 5

[params]
  footer_slogan = "<b>他们正热烈地讨论着别人的秘密，但是，一个不说，一个不听，还有一个不看。</b>"
  avatar_url = "https://i.loli.net/2019/07/28/5d3d4b6b925be18865.jpg"
  index_slogan = "<h1 style=\"color: pink;\">这个世界没那么好，但似乎也没那么糟。</h1>"

[[params.social_link]]
  name = "github"
  url = "https://github.com/creedowl"
  icon = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/github.svg"
  color = "#181717"

[[params.social_link]]
  name = "twitter"
  url = "https://twitter.com/creedowl_"
  icon = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/twitter.svg"
  color = "#1DA1F2"
