# develop configuration
contentDir = "exampleSite/content"
staticDir = "exampleSite/static"
themesDir = ".."

# site metadata
baseURL = "https://example.com/"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
languageCode = "zh-cn"
paginate = 5
theme = "hugo-theme-verse"
title = "Verse"

[author]
name = "<author>"

# site navigation bar
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 2
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 4

[params]
  avatar_round = true
  avatar_url = "https://i.loli.net/2020/02/26/yne2OuofTMS9CWD.png"
  description = "example site of hugo blog using theme Verse"
  enable_mathjax = true
  footnote = ""
  keywords = ["hugo", "theme", "Verse"]
  slogan = "<b>Cogito, ergo sum</b>"

[[params.social_link]]
  name = "gmail"
  url = "https://gmail.com"
  icon = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/gmail.svg"

[[params.social_link]]
  name = "github"
  url = "https://github.com/"
  icon = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/github.svg"

[[params.social_link]]
  name = "telegram"
  url = "https://telegram.org/"
  icon = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/telegram.svg"

[[params.social_link]]
  name = "twitter"
  url = "https://twitter.com/"
  icon = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/twitter.svg"
