# develop configuration
contentDir = "exampleSite/content"
staticDir = "exampleSite/static"
themesDir = ".."

# site metadata
baseURL = "https://example.com/"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
languageCode = "zh-cn"
paginate = 3
theme = "hugo-theme-texify"
title = "TeXify"

pygmentsUseClasses = true

[author]
name = "author"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# site navigation bar
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[params]
  description = "example site of hugo blog using theme TeXify"
  enable_mathjax = true
  footnote = "Follow me on <a class=link href=https://github.com/queensferryme>GitHub</a>, <a class=link href=https://twitter.com/queensferryme>Twitter</a> or <a class=link href=/index.xml>RSS</a>"
  keywords = ["hugo", "theme", "TeXify"]
